-- Minimal stand-ins for what Supabase provides and what earlier RoadStar
-- migrations created, so the new migration runs in plain PostgreSQL.
\set ON_ERROR_STOP on
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
end $$;

create schema auth;
create table auth.users (id uuid primary key);
-- Same resolution Supabase uses: the JWT subject of the current request.
create function auth.uid() returns uuid language sql stable
as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant usage on schema auth to anon, authenticated;
grant execute on function auth.uid() to anon, authenticated;

create schema storage;
create table storage.buckets (id text primary key, name text not null, public boolean default false, file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text references storage.buckets(id),
  name text not null,
  owner uuid,
  owner_id text,
  metadata jsonb,
  created_at timestamptz default now(),
  unique (bucket_id, name)
);
alter table storage.objects enable row level security;
grant usage on schema storage to anon, authenticated;
grant select, insert, update, delete on storage.objects to authenticated;
grant select on storage.buckets to authenticated;

create publication supabase_realtime;

create table public.organizations (id bigint generated by default as identity primary key, name text, slug text unique);
create table public.organization_members (
  organization_id bigint references public.organizations(id),
  user_id uuid references auth.users(id),
  role text not null check (role in ('admin', 'dispatcher', 'driver', 'viewer')),
  primary key (organization_id, user_id)
);
create table public.dispatch_snapshots (organization_id bigint primary key references public.organizations(id), state jsonb not null, revision bigint not null default 0);
create table public.driver_user_links (organization_id bigint, user_id uuid, driver_external_id text, primary key (organization_id, user_id));
create table public.system_health (id boolean primary key default true, schema_version text, installed_at timestamptz);
insert into public.system_health values (true, '20260913055147', now());
create schema private;
revoke all on schema private from public, anon, authenticated;
