create extension if not exists postgis with schema extensions;

do $$ begin
  create type public.load_status as enum ('unassigned', 'assigned', 'in_transit', 'completed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.asset_status as enum ('available', 'assigned', 'maintenance', 'inactive');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.duty_status as enum ('off_duty', 'sleeper', 'driving', 'on_duty');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.plan_status as enum ('draft', 'proposed', 'approved', 'superseded');
exception when duplicate_object then null;
end $$;

create table public.system_health (
  id boolean primary key default true check (id),
  schema_version text not null,
  installed_at timestamptz not null default now()
);

insert into public.system_health (schema_version) values ('202609100001');

create table public.organizations (
  id bigint generated always as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table public.organization_members (
  organization_id bigint not null references public.organizations on delete cascade,
  user_id uuid not null references auth.users on delete cascade,
  role text not null default 'dispatcher' check (role in ('admin', 'dispatcher', 'driver', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table public.drivers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  external_id text unique,
  name text not null,
  email text,
  status public.asset_status not null default 'available',
  duty_status public.duty_status not null default 'off_duty',
  remaining_hours numeric(6,2),
  cycle integer,
  current_location extensions.geography(point, 4326),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.trucks (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  truck_number text not null unique,
  status public.asset_status not null default 'available',
  current_location extensions.geography(point, 4326),
  odometer_km numeric(12,2),
  created_at timestamptz not null default now()
);

create table public.trailers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  trailer_number text not null unique,
  trailer_type text not null,
  capacity_lbs numeric(10,2) not null check (capacity_lbs > 0),
  length_in integer not null check (length_in > 0),
  width_in integer not null check (width_in > 0),
  inside_height_in integer not null check (inside_height_in > 0),
  status public.asset_status not null default 'available',
  created_at timestamptz not null default now()
);

create table public.loads (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  bill_number text not null unique,
  description text,
  status public.load_status not null default 'unassigned',
  load_type text not null,
  origin_city text not null,
  origin_province text,
  destination_city text not null,
  destination_province text,
  pickup_window_start timestamptz,
  pickup_window_end timestamptz,
  delivery_window_start timestamptz,
  delivery_window_end timestamptz,
  weight_lbs numeric(10,2) check (weight_lbs >= 0),
  pallet_count integer check (pallet_count >= 0),
  temperature_controlled boolean not null default false,
  temperature text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  load_id bigint not null references public.loads on delete cascade,
  driver_id bigint references public.drivers,
  truck_id bigint references public.trucks,
  trailer_id bigint references public.trailers,
  assigned_at timestamptz not null default now(),
  accepted_at timestamptz,
  completed_at timestamptz,
  unique (load_id)
);

create table public.loading_plans (
  id uuid primary key default gen_random_uuid(),
  organization_id bigint not null references public.organizations on delete cascade,
  trailer_id bigint not null references public.trailers,
  status public.plan_status not null default 'draft',
  solver text not null,
  total_weight_lbs numeric(10,2) not null default 0,
  utilization numeric(6,3),
  warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.loading_plan_items (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  loading_plan_id uuid not null references public.loading_plans on delete cascade,
  load_id bigint references public.loads,
  external_item_id text not null,
  stop_sequence integer not null,
  x_in integer not null,
  y_in integer not null,
  z_in integer not null,
  length_in integer not null,
  width_in integer not null,
  height_in integer not null,
  weight_lbs numeric(10,2) not null,
  rotated boolean not null default false,
  estimated boolean not null default false
);

create table public.facilities (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  name text not null,
  address text,
  location extensions.geography(point, 4326) not null,
  geofence extensions.geography(polygon, 4326),
  free_detention_minutes integer not null default 120
);

create table public.telemetry_points (
  id bigint generated always as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  truck_id bigint not null references public.trucks on delete cascade,
  recorded_at timestamptz not null default now(),
  location extensions.geography(point, 4326) not null,
  speed_kph numeric(6,2),
  odometer_km numeric(12,2)
);

create table public.geofence_events (
  id bigint generated always as identity primary key,
  organization_id bigint not null references public.organizations on delete cascade,
  truck_id bigint not null references public.trucks,
  facility_id bigint not null references public.facilities,
  event_type text not null check (event_type in ('arrived', 'departed')),
  occurred_at timestamptz not null,
  location extensions.geography(point, 4326)
);

create index drivers_location_gix on public.drivers using gist (current_location);
create index trucks_location_gix on public.trucks using gist (current_location);
create index facilities_location_gix on public.facilities using gist (location);
create index facilities_geofence_gix on public.facilities using gist (geofence);
create index telemetry_location_gix on public.telemetry_points using gist (location);
create index telemetry_truck_time_idx on public.telemetry_points (truck_id, recorded_at desc);
create index geofence_truck_time_idx on public.geofence_events (truck_id, occurred_at desc);
create index organization_members_user_idx on public.organization_members (user_id);
create index drivers_organization_idx on public.drivers (organization_id);
create index trucks_organization_idx on public.trucks (organization_id);
create index trailers_organization_idx on public.trailers (organization_id);
create index loads_organization_idx on public.loads (organization_id);
create index assignments_organization_idx on public.assignments (organization_id);
create index assignments_driver_idx on public.assignments (driver_id);
create index assignments_truck_idx on public.assignments (truck_id);
create index assignments_trailer_idx on public.assignments (trailer_id);
create index loading_plans_organization_idx on public.loading_plans (organization_id);
create index loading_plans_trailer_idx on public.loading_plans (trailer_id);
create index loading_plan_items_organization_idx on public.loading_plan_items (organization_id);
create index loading_plan_items_plan_idx on public.loading_plan_items (loading_plan_id);
create index loading_plan_items_load_idx on public.loading_plan_items (load_id);
create index facilities_organization_idx on public.facilities (organization_id);
create index telemetry_organization_idx on public.telemetry_points (organization_id);
create index geofence_organization_idx on public.geofence_events (organization_id);
create index geofence_facility_idx on public.geofence_events (facility_id);

alter table public.system_health enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.drivers enable row level security;
alter table public.trucks enable row level security;
alter table public.trailers enable row level security;
alter table public.loads enable row level security;
alter table public.assignments enable row level security;
alter table public.loading_plans enable row level security;
alter table public.loading_plan_items enable row level security;
alter table public.facilities enable row level security;
alter table public.telemetry_points enable row level security;
alter table public.geofence_events enable row level security;

create policy "public can read system health" on public.system_health
  for select to anon, authenticated using (true);

create policy "members can read their membership" on public.organization_members
  for select to authenticated using (user_id = (select auth.uid()));

create policy "members can read their organizations" on public.organizations
  for select to authenticated using (
    id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
  );

create policy "members can read drivers" on public.drivers for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read trucks" on public.trucks for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read trailers" on public.trailers for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read loads" on public.loads for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read assignments" on public.assignments for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read loading plans" on public.loading_plans for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read loading plan items" on public.loading_plan_items for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read facilities" on public.facilities for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read telemetry" on public.telemetry_points for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);
create policy "members can read geofence events" on public.geofence_events for select to authenticated using (
  organization_id in (select organization_id from public.organization_members where user_id = (select auth.uid()))
);

grant usage on schema public to authenticated;
grant usage on schema public to anon;
grant select on public.system_health to anon, authenticated;
grant select on public.organizations, public.organization_members, public.drivers, public.trucks,
  public.trailers, public.loads, public.assignments, public.loading_plans,
  public.loading_plan_items, public.facilities, public.telemetry_points,
  public.geofence_events to authenticated;

