create extension if not exists postgis with schema extensions;

create type public.load_status as enum ('unassigned', 'assigned', 'in_transit', 'completed', 'cancelled');
create type public.asset_status as enum ('available', 'assigned', 'maintenance', 'inactive');
create type public.duty_status as enum ('off_duty', 'sleeper', 'driving', 'on_duty');
create type public.plan_status as enum ('draft', 'proposed', 'approved', 'superseded');

create table public.drivers (
  id bigint generated by default as identity primary key,
  external_id text unique,
  name text not null,
  email text,
  status public.asset_status not null default 'available',
  duty_status public.duty_status not null default 'off_duty',
  remaining_hours numeric(6,2),
  cycle integer,
  current_location extensions.geography(point, 4326),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.trucks (
  id bigint generated by default as identity primary key,
  truck_number text not null unique,
  status public.asset_status not null default 'available',
  current_location extensions.geography(point, 4326),
  odometer_km numeric(12,2),
  created_at timestamptz not null default now()
);

create table public.trailers (
  id bigint generated by default as identity primary key,
  trailer_number text not null unique,
  trailer_type text not null,
  capacity_lbs numeric(10,2) not null check (capacity_lbs > 0),
  length_in integer not null check (length_in > 0),
  width_in integer not null check (width_in > 0),
  inside_height_in integer not null check (inside_height_in > 0),
  status public.asset_status not null default 'available',
  created_at timestamptz not null default now()
);

create table public.loads (
  id bigint generated by default as identity primary key,
  bill_number text not null unique,
  description text,
  status public.load_status not null default 'unassigned',
  load_type text not null,
  origin_city text not null,
  origin_province text,
  destination_city text not null,
  destination_province text,
  pickup_window_start timestamptz,
  pickup_window_end timestamptz,
  delivery_window_start timestamptz,
  delivery_window_end timestamptz,
  weight_lbs numeric(10,2) check (weight_lbs >= 0),
  pallet_count integer check (pallet_count >= 0),
  temperature_controlled boolean not null default false,
  temperature text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  load_id bigint not null references public.loads on delete cascade,
  driver_id bigint references public.drivers,
  truck_id bigint references public.trucks,
  trailer_id bigint references public.trailers,
  assigned_at timestamptz not null default now(),
  accepted_at timestamptz,
  completed_at timestamptz,
  unique (load_id)
);

create table public.loading_plans (
  id uuid primary key default gen_random_uuid(),
  trailer_id bigint not null references public.trailers,
  status public.plan_status not null default 'draft',
  solver text not null,
  total_weight_lbs numeric(10,2) not null default 0,
  utilization numeric(6,3),
  warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.loading_plan_items (
  id bigint generated by default as identity primary key,
  loading_plan_id uuid not null references public.loading_plans on delete cascade,
  load_id bigint references public.loads,
  external_item_id text not null,
  stop_sequence integer not null,
  x_in integer not null,
  y_in integer not null,
  z_in integer not null,
  length_in integer not null,
  width_in integer not null,
  height_in integer not null,
  weight_lbs numeric(10,2) not null,
  rotated boolean not null default false,
  estimated boolean not null default false
);

create table public.facilities (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  location extensions.geography(point, 4326) not null,
  geofence extensions.geography(polygon, 4326),
  free_detention_minutes integer not null default 120
);

create table public.telemetry_points (
  id bigint generated always as identity primary key,
  truck_id bigint not null references public.trucks on delete cascade,
  recorded_at timestamptz not null default now(),
  location extensions.geography(point, 4326) not null,
  speed_kph numeric(6,2),
  odometer_km numeric(12,2)
);

create table public.geofence_events (
  id bigint generated always as identity primary key,
  truck_id bigint not null references public.trucks,
  facility_id bigint not null references public.facilities,
  event_type text not null check (event_type in ('arrived', 'departed')),
  occurred_at timestamptz not null,
  location extensions.geography(point, 4326)
);

create index drivers_location_gix on public.drivers using gist (current_location);
create index trucks_location_gix on public.trucks using gist (current_location);
create index facilities_location_gix on public.facilities using gist (location);
create index facilities_geofence_gix on public.facilities using gist (geofence);
create index telemetry_location_gix on public.telemetry_points using gist (location);
create index telemetry_truck_time_idx on public.telemetry_points (truck_id, recorded_at desc);
create index geofence_truck_time_idx on public.geofence_events (truck_id, occurred_at desc);

alter table public.drivers enable row level security;
alter table public.trucks enable row level security;
alter table public.trailers enable row level security;
alter table public.loads enable row level security;
alter table public.assignments enable row level security;
alter table public.loading_plans enable row level security;
alter table public.loading_plan_items enable row level security;
alter table public.facilities enable row level security;
alter table public.telemetry_points enable row level security;
alter table public.geofence_events enable row level security;

-- Development/demo read access. Replace with organization-scoped policies before production.
create policy "authenticated users can read drivers" on public.drivers for select to authenticated using (true);
create policy "authenticated users can read trucks" on public.trucks for select to authenticated using (true);
create policy "authenticated users can read trailers" on public.trailers for select to authenticated using (true);
create policy "authenticated users can read loads" on public.loads for select to authenticated using (true);
create policy "authenticated users can read assignments" on public.assignments for select to authenticated using (true);
create policy "authenticated users can read loading plans" on public.loading_plans for select to authenticated using (true);
create policy "authenticated users can read loading plan items" on public.loading_plan_items for select to authenticated using (true);
create policy "authenticated users can read facilities" on public.facilities for select to authenticated using (true);
create policy "authenticated users can read telemetry" on public.telemetry_points for select to authenticated using (true);
create policy "authenticated users can read geofence events" on public.geofence_events for select to authenticated using (true);

